Repository NewSpring/Apollos, pull requests merged in 2018-03, with the labels that each got.

#375 Input Validation Text
  src/@ui/forms/BillingAddressForm.js
  src/@ui/forms/ChangePasswordForm.js
  src/@ui/forms/ChangePaymentMethodForm.js
  src/@ui/forms/EditSavedPaymentMethodForm.js
  src/@ui/forms/ForgotPasswordForm.js
  src/@ui/forms/LoginForm.js
  src/@ui/forms/PaymentForm.js
  src/@ui/forms/PersonalDetailsForm.js
  src/@ui/forms/ProfileAddressForm.js
  src/@ui/forms/ProfileDetailsForm.js
  src/@ui/forms/SignUpForm.js
Labels: merge

#382 379 updated meta description
  src/@ui/Meta/__tests__/__snapshots__/index.js.snap
  src/@ui/Meta/metadata.js
Labels: merge

#381 247 giving min amount
  src/@ui/forms/ContributionForm/index.js
Labels: merge

#378 Modal Styles
  src/@ui/Hero/Hero.stories.js
  src/@ui/ModalView/index.js
  src/@ui/SideBySideView/Left.js
  src/@ui/VideoPlayer/Video.web.js
  src/@ui/VideoPlayer/index.js
  src/@ui/theme/defaultTheme.js
  src/AppRouter.js
  src/auth/ForgotPassword.js
  src/auth/index.js
  src/tabs/Discover/index.js
  src/tabs/Feed.js
  src/tabs/Sections.js
Labels: merge

#385 369 Netlify toml
  .scripts/generate-env-files.js
  netlify.toml
  package.json
Labels: merge

#390 Updated Context Branch Names
  netlify.toml
Labels: merge

#384 367 Live Redirect
  src/@data/withLiveNow/index.js
  src/@ui/LiveNowButton/index.js
  src/live/index.js
Labels: merge

#377 374 giving history
  src/@data/utils/fetchMoreResolver.js
  src/@data/withTransactions/withTransactions.js
  src/give/ContributionHistory/ContributionHistoryList.js
  src/give/ContributionHistory/index.js
Labels: merge

#373 324 Reset State on Logout
  src/@data/Client/clearCache.js
  src/@data/withUser/withLogin.js
  src/@data/withUser/withLogout.js
  src/@ui/NativeWebRouter/Link.js
  src/@ui/NativeWebRouter/ProtectedRoute.js
  src/@ui/RelatedContent/RelatedContentWithoutData.js
  src/@ui/WebCompatibleFlatList/index.web.js
  src/@utils/pickProps.js
  src/settings/index.js
  src/tabs/Profile/Likes.js
Labels: ready for review

#338 Sermon audio
  src/@data/mediaPlayer/albumsQuery.js
  src/@data/mediaPlayer/index.js
  src/@data/mediaPlayer/mediaPlayerQuery.js
  src/@data/mediaPlayer/mutations.js
  src/@data/mediaPlayer/nowPlayingMutation.js
  src/@data/mediaPlayer/queries.js
  src/@ui/ContentView/ContentMedia.js
  src/@ui/ContentView/Media/AudioBanner/AudioBanner.stories.js
  src/@ui/ContentView/Media/AudioBanner/AudioBanner.tests.js
  src/@ui/ContentView/Media/AudioBanner/__snapshots__/AudioBanner.tests.js.snap
  src/@ui/ContentView/Media/AudioBanner/index.js
  src/@ui/ContentView/Media/ImageHeader.js
  src/@ui/ContentView/Media/VideoHeader.js
  src/@ui/ContentView/Media/index.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/ContentView/index.js
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedItemCard/index.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/GradientOverlayImage/index.js
  src/music/Player/FullScreenControls.js
  src/music/Player/FullScreenControls.tests.js
  src/music/Player/MiniControls.js
  src/music/Player/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/__snapshots__/MiniControls.tests.js.snap
  src/music/Player/index.js
  src/music/Playlist.js
  src/series/Sermon.js
Labels: ready for review

#395 updated branch names
  netlify.toml
Labels: merge

#397 Update master netlify settings
  netlify.toml
Labels: merge

#400 392 help link
  src/give/Now.js
Labels: merge

#401 368 Giving flow style fixes
  src/@ui/AccountCard/__snapshots__/AccountCard.tests.js.snap
  src/@ui/CashAmountIndicator/index.js
  src/@ui/Icon/__snapshots__/Icon.tests.js.snap
  src/@ui/Icon/icons/Bank.js
  src/@ui/SecondaryNav/__snapshots__/SecondaryNav.tests.js.snap
  src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
  src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap
  src/give/Checkout/Failure.js
  src/give/Success.js
Labels: waiting for changes

#404 Updating Apollos Assets
  app-config.js
  public/index.html
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/assets/splash/android/1080_1440.png
  src/assets/splash/android/320_470.png
  src/assets/splash/android/480_640.png
  src/assets/splash/android/720_960.png
  src/assets/splash/android/splash-1080x1440.png
  src/assets/splash/android/splash-320x470.png
  src/assets/splash/android/splash-480x640.png
  src/assets/splash/android/splash-720x960.png
  src/assets/splash/ios/768_1024.png
  src/assets/splash/ios/splash-768x1024.png
  src/assets/splash/splash-1242x2436.png
Labels: merge

#410 updated background color
  app-config.js
Labels: merge

#403 365 image uploads
  src/@ui/Avatar/index.js
  src/@ui/ConnectedImage/index.js
  src/@ui/UserAvatarView/index.js
  src/@ui/forms/UploadProfileImageForm/index.js
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@utils/makeCancelable.js
Labels: merge

#398 312 closing media player
  .travis.yml
  src/@data/mediaPlayer/index.js
  src/@data/mediaPlayer/mutations.js
  src/@data/mediaPlayer/stopMutation.js
  src/music/Player/FullScreenControls/FullScreenControls.tests.js
  src/music/Player/FullScreenControls/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/FullScreenControls/index.js
  src/music/Player/MiniControls/MiniControls.tests.js
  src/music/Player/MiniControls/MiniControlsThumbnail/MiniControlsThumbnail.stories.js
  src/music/Player/MiniControls/MiniControlsThumbnail/MiniControlsThumbnail.tests.js
  src/music/Player/MiniControls/MiniControlsThumbnail/__snapshots__/MiniControlsThumbnail.tests.js.snap
  src/music/Player/MiniControls/MiniControlsThumbnail/index.js
  src/music/Player/MiniControls/__snapshots__/MiniControls.tests.js.snap
  src/music/Player/MiniControls/index.js
  src/music/Player/index.js
  yarn.lock
Labels: ready for review

#423 420 Content Titles
  src/@ui/ContentView/ByLine.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/ContentView/index.js
  src/@ui/typography/H6/index.js
Labels: merge

#434 329 profile birthday
  src/@ui/forms/ProfileDetailsForm.js
  src/@ui/inputs/DateInput/DateInput.tests.js
  src/@ui/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
Labels: merge

#435 386 fixing scripture songs
  src/@ui/Scripture/Scripture.stories.js
  src/@ui/Scripture/Scripture.tests.js
  src/@ui/Scripture/ScriptureHTMLView.js
  src/@ui/Scripture/__snapshots__/Scripture.tests.js.snap
Labels: merge

#436 Giving / Checkout fixes
  src/@data/utils/identifyCategory.js
  src/@ui/FeedView/index.js
  src/@ui/TransactionCard/StatusMessage.js
  src/@ui/TransactionCard/__snapshots__/TransactionCard.tests.js.snap
  src/@ui/forms/PaymentConfirmationForm.js
  src/@ui/forms/SignUpForm.js
  src/give/AddAccount/index.js
  src/give/Checkout/Failure.js
  src/give/Checkout/index.js
  src/give/RestoredCheckout.js
Labels: merge

#438 Update env script Token
  .scripts/generate-env-files.js
Labels: merge

#439 409 Second address field validation fix
  src/@ui/forms/BillingAddressForm.js
Labels: ready for review

#441 Password Reset Form Issues
  src/@ui/forms/ForgotPasswordForm.js
Labels: merge

#325 supposedly add support for iOS AppLinks
  android/build/android-profile/profile-2018-03-29-09-26-08-584.rawproto
  android/build/android-profile/profile-2018-03-29-09-31-01-667.rawproto
  package.json
  src/@ui/NativeWebRouter/DeepLinking.js
  src/@utils/getAppPathForUrl.js
  src/AppRouter.js
  src/tabs/Discover/Results.js
  yarn.lock
Labels: merge

#411 408 - Refresh queries after giving
  src/@data/withGive/setPaymentResult.js
  src/@data/withGivingDashboard/index.js
  src/give/Checkout/PaymentComplete.js
Labels: merge
