Repository NewSpring/Apollos, pull requests merged in 2018-04, with the labels that each got.

#445 Fix DeepLinking white screen on app load
  src/@ui/NativeWebRouter/DeepLinking.js
  yarn.lock
Labels: merge

#443 Fix the white screen delay when loading app
  src/@ui/FontLoader/index.js
Labels: merge

#446 Alpha 6.0.0 to Beta 6.0.0
  .scripts/generate-env-files.js
  android/build/android-profile/profile-2018-03-29-09-26-08-584.rawproto
  android/build/android-profile/profile-2018-03-29-09-31-01-667.rawproto
  package.json
  src/@data/utils/identifyCategory.js
  src/@data/withGive/setPaymentResult.js
  src/@data/withGivingDashboard/index.js
  src/@ui/ContentView/ByLine.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/ContentView/index.js
  src/@ui/FeedView/index.js
  src/@ui/FontLoader/index.js
  src/@ui/NativeWebRouter/DeepLinking.js
  src/@ui/Scripture/Scripture.stories.js
  src/@ui/Scripture/Scripture.tests.js
  src/@ui/Scripture/ScriptureHTMLView.js
  src/@ui/Scripture/__snapshots__/Scripture.tests.js.snap
  src/@ui/TransactionCard/StatusMessage.js
  src/@ui/TransactionCard/__snapshots__/TransactionCard.tests.js.snap
  src/@ui/forms/BillingAddressForm.js
  src/@ui/forms/ChangePaymentMethodForm.js
  src/@ui/forms/ForgotPasswordForm.js
  src/@ui/forms/PaymentConfirmationForm.js
  src/@ui/forms/ProfileDetailsForm.js
  src/@ui/forms/SignUpForm.js
  src/@ui/inputs/DateInput/DateInput.tests.js
  src/@ui/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  src/@ui/typography/H6/index.js
  src/@utils/getAppPathForUrl.js
  src/AppRouter.js
  src/give/AddAccount/index.js
  src/give/Checkout/Failure.js
  src/give/Checkout/PaymentComplete.js
  src/give/Checkout/index.js
  src/give/RestoredCheckout.js
  src/tabs/Discover/Results.js
  yarn.lock
Labels: release

#448 remove polling and fix give flow
  src/@data/withGivingDashboard/index.js
  src/@data/withLiveNow/index.js
  src/@ui/NativeWebRouter/DeepLinking.js
Labels: merge

#449 Give hotfix
  src/@data/withGivingDashboard/index.js
Labels: merge

#451 fix story heading #389
  src/stories/Single.js
Labels: merge

#452 428 Fix contact us button on group finder
  src/group-finder/AdUnit.js
Labels: merge

#458 Fix issue allowing group search with no input
  package.json
  src/@ui/forms/GroupSearchForm/index.js
  yarn.lock
Labels: ready for review

#453 Fix issue with universal link loading
  app-config.js
  package.json
  src/@data/Client/errorLink.js
  src/@data/Client/index.js
  src/@ui/NativeWebRouter/DeepLinking.js
  src/AppRouter.js
  yarn.lock
Labels: merge

#447 fix issue where can't open scheme-less links
  src/@ui/HTMLView/index.js
Labels: merge

#463 Performance: progressive image loading
  src/@data/fragments.js
  src/@data/likes/fragments.js
  src/@data/mediaPlayer/albumQuery.js
  src/@data/mediaPlayer/albumsQuery.js
  src/@data/withArticle/articleQuery.js
  src/@data/withArticles/articlesQuery.js
  src/@data/withDevotional/devotionalQuery.js
  src/@data/withDevotionals/devotionalsQuery.js
  src/@data/withEvent/eventQuery.js
  src/@data/withHomeFeed/homeFeedQuery.js
  src/@data/withNewsStories/newsStoriesQuery.js
  src/@data/withNewsStory/newsStoryQuery.js
  src/@data/withPromotions/promotionsQuery.js
  src/@data/withRelatedContent/relatedContentQuery.js
  src/@data/withSeries/seriesQuery.js
  src/@data/withSeriesContent/seriesContentQuery.js
  src/@data/withSeriesSermon/seriesSermonQuery.js
  src/@data/withSermon/sermonQuery.js
  src/@data/withStories/storiesQuery.js
  src/@data/withStory/storyQuery.js
  src/@data/withStudies/studiesQuery.js
  src/@data/withStudy/studyQuery.js
  src/@data/withStudyEntries/studyEntriesQuery.js
  src/@data/withStudyEntry/studyEntryQuery.js
  src/@data/withTaggedContent/index.js
  src/@ui/AlbumView/__snapshots__/AlbumView.tests.js.snap
  src/@ui/AlbumView/index.js
  src/@ui/Card/Image.js
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/ConnectedImage/ConnectedImage.tests.js
  src/@ui/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  src/@ui/ConnectedImage/index.js
  src/@ui/ContentView/Media/ImageHeader.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/ContentView/index.js
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedItemCard/index.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/FeedView/index.js
  src/@ui/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  src/@ui/GradientOverlayImage/index.js
  src/@ui/ProgressiveImage/ProgressiveImage.tests.js
  src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap
  src/@ui/ProgressiveImage/index.js
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/ThumbnailCard/Thumbnail.js
  src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  src/@ui/ThumbnailCard/index.js
  src/@ui/TileNav/NavItemImage.js
  src/@utils/content/getItemThumbnail.js
  src/@utils/content/index.js
  src/give/Funds/FundCard.js
  src/group-finder/GroupCard.js
  src/group-finder/GroupSingle.js
  src/music/Player/FullScreenControls/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/MiniControls/__snapshots__/MiniControls.tests.js.snap
Labels: merge

#462 Performance: Splash Screen
  app-config.js
Labels: merge

#460 Tweak copy for iOS checkout
  src/@ui/forms/PaymentConfirmationForm.js
  src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
Labels: merge

#464 Performance: content placeholders
  package.json
  src/@data/Client/cache.js
  src/@data/likes/fragments.js
  src/@data/withArticle/index.js
  src/@data/withArticles/articlesQuery.js
  src/@data/withCachedContent/index.js
  src/@data/withNewsStories/newsStoriesQuery.js
  src/@data/withNewsStory/index.js
  src/@data/withPromotions/promotionsQuery.js
  src/@data/withRelatedContent/relatedContentQuery.js
  src/@data/withSeriesContent/seriesContentQuery.js
  src/@data/withSermon/sermonQuery.js
  src/@data/withStories/storiesQuery.js
  src/@data/withStory/index.js
  src/@ui/ContentView/index.js
  src/articles/Single.js
  src/news/Single.js
  src/series/Sermon.js
  src/series/Single.js
  src/stories/Single.js
  src/studies/Entry/DevotionalTab.js
  src/studies/Entry/EntryList.js
  src/studies/Entry/index.js
  src/studies/Single.js
  yarn.lock
Labels: merge

#444 Onboarding
  package.json
  src/@data/Client/authenticationLink.js
  src/@data/Client/clientStateLink.js
  src/@data/withOnboarding/index.js
  src/@data/withOnboarding/mutationResolvers.js
  src/@data/withOnboarding/query.js
  src/@data/withOnboarding/queryResolvers.js
  src/@data/withRestoredGive/index.js
  src/@data/withUser/withLogin.js
  src/@data/withUser/withRegister.js
  src/@data/withUser/withResetPassword.js
  src/@ui/Audio/Audio.stories.js
  src/@ui/Audio/AudioPause.js
  src/@ui/Audio/AudioPlay.js
  src/@ui/ContributionsChart/index.js
  src/@ui/DashboardSubheader/index.js
  src/@ui/ExpiringAccountCard/index.js
  src/@ui/NativeWebRouter/Router.js
  src/@ui/Onboarding/Onboarding.stories.js
  src/@ui/Onboarding/__tests__/__snapshots__/index.js.snap
  src/@ui/Onboarding/__tests__/index.js
  src/@ui/Onboarding/index.js
  src/@ui/Onboarding/index.web.js
  src/@ui/OnboardingModal/index.js
  src/@ui/OnboardingModal/index.web.js
  src/@ui/ScheduleCard/index.js
  src/@ui/TransactionCard/index.js
  src/@ui/forms/DeleteSavedPaymentMethodButton.js
  src/@ui/forms/ResetPasswordForm.js
  src/@ui/inputs/Radio/RadioButtonIndicator.js
  src/@ui/inputs/Radio/index.js
  src/@utils/queryString.js
  src/assets/onboarding/1-Welcome.jpg
  src/assets/onboarding/2-Stories.jpg
  src/assets/onboarding/3-Sermons.jpg
  src/assets/onboarding/4-Music.jpg
  src/assets/onboarding/5-Scripture.jpg
  src/assets/onboarding/6-Favorites.jpg
  src/assets/onboarding/7-Campus.jpg
  src/assets/onboarding/8-Get-Started.jpg
  src/give/RestoredCheckout.js
  src/give/TransactionDetails/Transaction.js
  src/index.js
  src/settings/index.js
  yarn.lock
Labels: merge

#467 Fix contribution chart history link
  src/@ui/ContributionsChartCard/index.js
  src/give/Dashboard.js
Labels: merge

#468 update build numbers
  app-config.js
Labels: ready for review

#391 Update Netlify.toml for Production
  README.md
  netlify.toml
Labels: merge

#475 Fixes onboarding to not try to show up on web
  src/@ui/OnboardingModal/index.web.js
Labels: ready for review

#477 Merge conflicts a b
  src/@data/withGivingDashboard/index.js
  src/@ui/NativeWebRouter/DeepLinking.js
  src/AppRouter.js
  yarn.lock
Labels: ready for review

#482 Fixed validation on form load
  src/@ui/forms/PaymentForm.js
Labels: merge

#481 fix for splash screen weirdness
  app-config.js
Labels: merge

#480 416-giving-confusion
  src/@ui/forms/PaymentConfirmationForm.js
  src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
Labels: ready for review

#483 Crashes
  package.json
  src/@data/utils/fetchMoreResolver.js
  src/@ui/forms/DeleteSavedPaymentMethodButton.js
  src/group-finder/GroupSingle.js
  src/group-finder/Results.js
  yarn.lock
Labels: ready for review

#499 Fix android back button
  src/@ui/CardStack/Transitioner.js
  src/music/Player/index.js
Labels: ready for review

#485 implement Amplitude
  .scripts/generate-env-files.js
  public/index.html
  src/@data/likes/withToggleLike.js
  src/@data/mediaPlayer/mutations.js
  src/@data/withGive/setPaymentResult.js
  src/@data/withUser/withForgotPassword.js
  src/@data/withUser/withLogin.js
  src/@data/withUser/withRegister.js
  src/@ui/forms/ContributionForm/index.js
  src/@ui/forms/PaymentConfirmationForm.js
  src/@utils/analytics/index.js
  src/@utils/analytics/instance.js
  src/@utils/analytics/instance.web.js
  src/@utils/content/share.js
  src/@utils/trackAppState.js
  src/AppRouter.js
  src/SentryContext.js
  src/give/Now.js
  src/group-finder/GroupSingle.js
  src/index.js
Labels: merge

#490 Give as Guest Button
  src/@ui/MediaQuery/MediaQuery.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/index.js
Labels: merge

#497 Fix Change Payment Method Button Link
  src/@ui/forms/PaymentConfirmationForm.js
  src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
Labels: merge

#501 Network related crashes
  package.json
  src/@data/Client/index.js
  src/@data/likes/withProfileLikes.js
  src/@data/likes/withProfileRecentLikes.js
  src/@data/likes/withRecentLikes.js
  src/@data/mediaPlayer/index.js
  src/@data/withArticle/index.js
  src/@data/withArticles/index.js
  src/@data/withCachedContent/index.js
  src/@data/withCampuses/index.js
  src/@data/withCashTag/index.js
  src/@data/withDevotional/index.js
  src/@data/withDevotionals/index.js
  src/@data/withEvent/index.js
  src/@data/withFilterContent/index.js
  src/@data/withFinancialAccounts/index.js
  src/@data/withGeoLocation/index.js
  src/@data/withGive/withContributions.js
  src/@data/withGroupAttributes/index.js
  src/@data/withGroupFinderResults/index.js
  src/@data/withGroupInfo/index.js
  src/@data/withLiveNow/index.js
  src/@data/withNewsStories/index.js
  src/@data/withNewsStory/index.js
  src/@data/withOnboarding/index.js
  src/@data/withPromotions/index.js
  src/@data/withRelatedContent/index.js
  src/@data/withSavedPaymentMethod/withSavedPaymentMethod.js
  src/@data/withSavedPaymentMethod/withSavedPaymentMethods.js
  src/@data/withScheduledTransaction/index.js
  src/@data/withScheduledTransactions/index.js
  src/@data/withScripture/index.js
  src/@data/withSearch/index.js
  src/@data/withSeries/index.js
  src/@data/withSeriesContent/index.js
  src/@data/withSeriesSermon/index.js
  src/@data/withSermon/index.js
  src/@data/withStories/index.js
  src/@data/withStory/index.js
  src/@data/withStudies/index.js
  src/@data/withStudy/index.js
  src/@data/withStudyEntries/index.js
  src/@data/withStudyEntry/index.js
  src/@data/withTaggedContent/index.js
  src/@data/withTopics/withAvailableTopics.js
  src/@data/withTransaction/index.js
  src/@data/withTransactions/withTransactions.js
  src/@data/withUser/withIsLoggedIn.js
  src/@data/withUser/withUser.js
  src/@ui/ErrorCard.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/FeedView/index.js
  src/@ui/RelatedContent/RelatedContentWithoutData.js
  src/@ui/forms/ContributionForm/index.js
  src/@utils/content/getLinkPath.js
  src/music/Player/index.js
  src/tabs/Discover/Feed.js
  src/tabs/Profile/Likes.js
  src/tabs/Profile/Topics.js
  yarn.lock
Labels: ready for review

#503 fix ability to view deprecated devotions
  src/AppRouter.js
  src/devotionals/index.js
  src/studies/Entry/DevotionalTab.js
  src/studies/Entry/ScriptureTab.js
  src/studies/Entry/index.js
Labels: ready for review

#506 Only track user if user is logged in
  src/SentryContext.js
Labels: ready for review

#507 Amplitude id fix
  src/SentryContext.js
Labels: ready for review

#508 Universal linking stability
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
  src/@ui/LiveNowButton/index.js
  src/AppRouter.js
Labels: merge

#510 Fix restored checkout in giving
  package.json
  src/index.js
  yarn.lock
Labels: merge

#512 Update Beta
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
  package.json
  src/@data/withLiveNow/index.js
  src/@ui/FeedView/index.js
  src/@ui/LiveNowButton/index.js
  src/@utils/getAppPathForUrl.js
  src/AppRouter.js
  src/index.js
  src/live/index.js
  src/tabs/Discover/Feed.js
  src/tabs/Discover/ItemLink.js
  src/tabs/Discover/Results.js
  yarn.lock
Labels: ready for review

#509 Remove give as guest option in checkout
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/index.js
Labels: merge

#513 Update alpha to beta
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/index.js
Labels: merge

#515 Add restricted paths and use singleInstance for universal linking on android
  android/app/src/main/AndroidManifest.xml
Labels: merge

#518 Fixed the schedule history bug thing
  src/give/ScheduleDetails/ScheduleTransactionHistory.js
Labels: ready for review

#520 updated splash screen background color
  ios/newspring/Supporting/LaunchScreen.xib
Labels: merge

#523 Fix Fabric on iOS
  ios/newspring.xcodeproj/project.pbxproj
  ios/newspring/AppDelegate.m
Labels: merge

#524 Add outbound link tracking
  src/@ui/NativeWebRouter/Link.js
  src/@utils/analytics/index.js
Labels: merge

#525 Strip Billing info from SavedPayment orders
  src/@data/withGive/createOrder.js
  src/@data/withGive/selectors/getOrderDetails.js
Labels: merge

#527 Fix Schedule Card for Multiple Funds
  src/give/Dashboard.js
Labels: ready for review

#528 Scripture link devos
  src/@utils/scriptures/__tests__/scriptures.list.js
  src/@utils/scriptures/index.js
  src/@utils/scriptures/scriptures.list.js
  src/studies/Entry/DevotionalTab.js
  src/studies/Entry/index.js
Labels: ready for review

#530 Add logic to strip out bad links in HTMLViews
  src/@ui/HTMLView/HTMLView.tests.js
  src/@ui/HTMLView/__snapshots__/HTMLView.tests.js.snap
  src/@ui/HTMLView/index.js
Labels: merge

#531 Fix: Clear order state when adding an account
  src/@data/withGive/createSavePaymentOrder.js
  src/@data/withGive/index.js
  src/@ui/CardTile/__snapshots__/CardTile.tests.js.snap
  src/@ui/forms/SavedPaymentReviewForm.js
Labels: merge

#538 Update react-native-web
  package.json
  src/@ui/CardWrapper/CardWrapper.stories.js
  src/@ui/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  src/@ui/ConnectedImage/index.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedItemCard/index.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  src/@ui/ModalView/index.js
  src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/__snapshots__/FundInput.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap
  src/@ui/forms/__snapshots__/PersonalDetailsForm.tests.js.snap
  src/@ui/inputs/Picker/index.web.js
  src/@ui/inputs/Text/__snapshots__/Text.tests.js.snap
  src/@ui/inputs/withFocusAnimation.js
  src/index.js
  src/music/Player/FullScreenControls/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/MiniControls/__snapshots__/MiniControls.tests.js.snap
  src/tabs/Groups/index.js
  yarn.lock
Labels: merge

#554 Fixed TransactionCard Icon and Details to include Pendingsettlement
  src/@ui/TransactionCard/StatusMessage.js
  src/@ui/TransactionCard/index.js
Labels: merge

#553 Hotfix for Giving Dashboard Icons and Sentry Breadcrumbs
  app-config.js
  package.json
  src/@ui/Button/Button.js
  src/@ui/Button/__snapshots__/Button.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/CardWrapper/CardWrapper.stories.js
  src/@ui/Chip/__snapshots__/Chip.tests.js.snap
  src/@ui/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  src/@ui/ConnectedImage/index.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedItemCard/index.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  src/@ui/ModalView/index.js
  src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/TransactionCard/StatusMessage.js
  src/@ui/TransactionCard/index.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/__snapshots__/FundInput.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap
  src/@ui/forms/__snapshots__/PersonalDetailsForm.tests.js.snap
  src/@ui/inputs/Picker/index.web.js
  src/@ui/inputs/Text/__snapshots__/Text.tests.js.snap
  src/@ui/inputs/withFocusAnimation.js
  src/@utils/analytics/index.js
  src/index.js
  src/music/Player/FullScreenControls/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/MiniControls/__snapshots__/MiniControls.tests.js.snap
  src/tabs/Groups/index.js
  yarn.lock
Labels: ready for review

#557 fix dateinput font on web
  src/@ui/inputs/DateInput/index.web.js
Labels: merge

#559 Hotfix
  app-config.js
  package.json
  src/@ui/Button/Button.js
  src/@ui/Button/__snapshots__/Button.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/CardWrapper/CardWrapper.stories.js
  src/@ui/Chip/__snapshots__/Chip.tests.js.snap
  src/@ui/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  src/@ui/ConnectedImage/index.js
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedItemCard/index.js
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  src/@ui/ModalView/index.js
  src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/TransactionCard/StatusMessage.js
  src/@ui/TransactionCard/index.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/__snapshots__/FundInput.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap
  src/@ui/forms/__snapshots__/PersonalDetailsForm.tests.js.snap
  src/@ui/inputs/Picker/index.web.js
  src/@ui/inputs/Text/__snapshots__/Text.tests.js.snap
  src/@ui/inputs/withFocusAnimation.js
  src/@utils/analytics/index.js
  src/index.js
  src/music/Player/FullScreenControls/__snapshots__/FullScreenControls.tests.js.snap
  src/music/Player/MiniControls/__snapshots__/MiniControls.tests.js.snap
  src/tabs/Groups/index.js
  yarn.lock
Labels: merge

#560 Fixed Watch Live Button
  src/@ui/LiveNowButton/index.js
Labels: merge

#564 Created ternary for web view of settings menu
  src/settings/index.js
Labels: ready for review
