Repository NewSpring/Apollos, pull requests merged in 2018-10, with the labels that each got.

#690 Google Analytics Integration
  android/app/build.gradle
  app.json
  package.json
  src/@data/likes/withToggleLike.js
  src/@data/mediaPlayer/mutations.js
  src/@data/withUser/withForgotPassword.js
  src/@data/withUser/withLogin.js
  src/@data/withUser/withRegister.js
  src/@ui/NativeWebRouter/Link.js
  src/@utils/analytics/google.android.js
  src/@utils/analytics/google.ios.js
  src/@utils/analytics/google.web.js
  src/@utils/analytics/index.js
  src/@utils/analytics/instance.js
  src/@utils/analytics/instance.web.js
  src/@utils/content/share.js
  src/SentryContext.js
  src/give/Now.js
  src/group-finder/GroupSingle.js
  yarn.lock
Labels: blocked

#699 Beta to Master
  android/app/build.gradle
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  android/app/src/main/res/drawable-hdpi/shell_launch_background_image.png
  android/app/src/main/res/drawable-mdpi/shell_launch_background_image.png
  android/app/src/main/res/drawable-xhdpi/shell_launch_background_image.png
  android/app/src/main/res/drawable-xxhdpi/shell_launch_background_image.png
  android/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png
  android/app/src/main/res/values/colors.xml
  android/gradle/wrapper/gradle-wrapper.properties
  app.json
  ios/Pods/ExpoKit/ios/Exponent/Kernel/Core/EXKernel.m
  ios/newspring.xcodeproj/project.pbxproj
  ios/newspring/Supporting/EXShell.plist
  ios/newspring/Supporting/Info.plist
  ios/newspring/Supporting/LaunchScreen.xib
  ios/newspring/Supporting/launch_background_image.png
  package-lock.json
  package.json
  src/@data/likes/withToggleLike.js
  src/@data/mediaPlayer/mutations.js
  src/@data/withUser/withForgotPassword.js
  src/@data/withUser/withLogin.js
  src/@data/withUser/withRegister.js
  src/@ui/NativeWebRouter/Link.js
  src/@ui/forms/ResetPasswordForm.js
  src/@utils/analytics/google.android.js
  src/@utils/analytics/google.ios.js
  src/@utils/analytics/google.web.js
  src/@utils/analytics/index.js
  src/@utils/analytics/instance.js
  src/@utils/analytics/instance.web.js
  src/@utils/content/share.js
  src/AppRouter.js
  src/SentryContext.js
  src/assets/splash/fall.2018.appsplash-NEW-03.png
  src/assets/splash/splash-1242x2436.png
  src/give/Now.js
  src/group-finder/GroupSingle.js
  yarn.lock
Labels: ready for review

#706 Fixed Misspelling in Saved Payment Form
  .github/PULL_REQUEST_TEMPLATE.md
  src/@ui/forms/SavedPaymentReviewForm.js
Labels: merge

#705 Fix Android 6.1.0 Crashing
  android/app/build.gradle
Labels: merge

#707 Release 6.1.1
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  app-config.js
  ios/newspring/Supporting/EXShell.plist
  src/@ui/forms/SavedPaymentReviewForm.js
Labels: ready for review
