Repository NewSpring/Apollos, pull requests merged in 2018-05, with the labels that each got.

#565 Fix issue when Button isn't supplied an onPress prop
  app-config.js
  package.json
  src/@ui/Button/Button.js
  src/@ui/Button/__snapshots__/Button.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/Chip/__snapshots__/Chip.tests.js.snap
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/settings/index.js
Labels: merge

#566 Hotfix v6.0.1
  app-config.js
  package.json
  src/@ui/Button/Button.js
  src/@ui/Button/__snapshots__/Button.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/Chip/__snapshots__/Chip.tests.js.snap
  src/@ui/LiveNowButton/index.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/inputs/DateInput/index.web.js
  src/settings/index.js
Labels: ready for review

#567 Hotfix v6.0.1
  app-config.js
  package.json
  src/@ui/Button/Button.js
  src/@ui/Button/__snapshots__/Button.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/Chip/__snapshots__/Chip.tests.js.snap
  src/@ui/LiveNowButton/index.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/inputs/DateInput/index.web.js
  src/settings/index.js
Labels: merge

#563 Make homepage on web the giving dashboard
  src/AppRouter.js
  src/tabs/Layout/index.js
Labels: merge

#556 fix page sizing for content feeds on web
  src/@ui/WebCompatibleFlatList/index.web.js
Labels: merge

#558 412 dollar sign
  src/@ui/forms/ContributionForm/FundInput.js
Labels: merge

#561 Fix centering / sizing of web background images
  src/@ui/ProgressiveImage/index.js
  src/@ui/ThumbnailCard/Thumbnail.js
  src/@ui/ThumbnailCard/index.js
  src/@ui/UserAvatarView/index.js
  src/group-finder/GroupCard.js
Labels: merge

#562 Secondary Nav Loading Fix
  src/@ui/SecondaryNav/index.js
  src/articles/Single.js
  src/group-finder/GroupSingle.js
  src/music/Playlist.js
  src/news/Single.js
  src/series/Sermon.js
  src/series/Single.js
  src/stories/Single.js
  src/studies/Entry/index.js
  src/studies/Single.js
Labels: merge

#570 569 improve network sentry errors
  src/@data/Client/errorLink.js
Labels: merge

#572 547 fix music player theming
  src/music/Player/FullScreenControls/index.js
  src/music/Player/index.js
Labels: merge

#568 Remove startCase from card titles & Update Snapshots
  src/@ui/FeedItemCard/index.js
Labels: merge

#581 Fix Travis builds that result in false passes
  .scripts/run-with-settings.js
  .scripts/test-script.sh
  .travis.yml
  package.json
  src/@ui/AlbumView/__snapshots__/AlbumView.tests.js.snap
  src/@ui/Card/__snapshots__/Card.tests.js.snap
  src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap
  src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap
  src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
Labels: merge

#574 Fix logout promise fullfillment and logout redirection on web
  src/@data/withUser/withLogout.js
  src/@utils/reload.js
  src/@utils/reload.web.js
  src/settings/index.js
Labels: merge

#583 Tablet Secondary Nav
  src/@ui/SecondaryNav/index.js
  src/articles/Single.js
  src/group-finder/GroupSingle.js
  src/music/Playlist.js
  src/news/Single.js
  src/series/Sermon.js
  src/series/Single.js
  src/stories/Single.js
  src/studies/Entry/index.js
  src/studies/Single.js
Labels: merge

#588 353 fix home feed category icons
  src/@ui/CategoryLabel/index.js
Labels: ready for review

#571 Normalize Address State field across forms
  src/@data/withCheckout/checkoutQuery.js
  src/@data/withGive/setBillingAddress.js
  src/@data/withUser/index.js
  src/@data/withUser/withAddressState.js
  src/@data/withUser/withUpdateHomeAddress.js
  src/@ui/forms/BillingAddressForm.js
  src/@ui/forms/ProfileAddressForm.js
Labels: merge

#596 update build numbers and version
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  app-config.js
  ios/newspring/Supporting/EXShell.plist
Labels: merge

#577 add formik setter HOCs for pure rendering of form inputs
  src/@ui/forms/BillingAddressForm/BillingAddressForm.tests.js
  src/@ui/forms/BillingAddressForm/GeographicPicker.js
  src/@ui/forms/BillingAddressForm/__snapshots__/BillingAddressForm.tests.js.snap
  src/@ui/forms/BillingAddressForm/index.js
  src/@ui/forms/ChangePasswordForm.js
  src/@ui/forms/ContributionForm/ContributionForm.tests.js
  src/@ui/forms/ForgotPasswordForm.js
  src/@ui/forms/GroupSearchForm/index.js
  src/@ui/forms/LoginForm.js
  src/@ui/forms/PaymentForm.js
  src/@ui/forms/PaymentForm.tests.js
  src/@ui/forms/PersonalDetailsForm.js
  src/@ui/forms/PersonalDetailsForm.tests.js
  src/@ui/forms/ProfileAddressForm.js
  src/@ui/forms/ProfileDetailsForm.js
  src/@ui/forms/ResetPasswordForm.js
  src/@ui/forms/SignUpForm.js
  src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap
  src/@ui/forms/__snapshots__/PersonalDetailsForm.tests.js.snap
  src/@ui/forms/__snapshots__/formikSetters.tests.js.snap
  src/@ui/forms/formikSetters.js
  src/@ui/forms/formikSetters.tests.js
  src/@ui/inputs/Picker/index.js
  src/@ui/inputs/Picker/index.web.js
Labels: ready for review

#597 Fix iOS checkout
  src/AppRouter.js
  src/tabs/Layout/index.js
Labels: merge

#600 updated package.json version
  package.json
Labels: merge

#601 updated package.json version (#600)
  package.json
Labels: merge

#603 Fix state to look for stateId
  src/@data/withGive/selectors/getOrderDetails.js
Labels: merge

#608 Fix secondary menu on group finder
  src/group-finder/GroupSingle.js
Labels: merge

#614 Release v6.0.2 HOTFIX
  src/@ui/forms/PaymentConfirmationForm.js
Labels: release

#615 Fix for the "All Time" giving history filter not working
  src/give/ContributionHistory/ContributionHistoryFilter.js
Labels: merge

#616 Fix circular reference potential in Sentry breadcrumb logging
  src/@ui/Button/Button.js
Labels: merge

#617 Update all the versions to 6.0.3
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  app-config.js
  ios/newspring/Supporting/EXShell.plist
  package.json
Labels: merge

#598 576 iOS Give Confirmation
  src/give/RestoredCheckout.js
Labels: merge

#611 perf optimizations
  src/@data/withGivingDashboard/index.js
  src/@ui/styled/createStyleSheet.js
  src/give/Dashboard.js
  src/give/RestoredCheckout.js
  src/give/ScheduleDetails/ScheduleTransactionHistory.js
Labels: discussion, merge

#638 Catch cancellable promise exception
  src/@ui/ConnectedImage/index.js
Labels: merge

#644 625 Antialiased typography on web
  src/@ui/typography/BodyText/index.js
  src/@ui/typography/H1/index.js
  src/@ui/typography/H2/index.js
  src/@ui/typography/H3/index.js
  src/@ui/typography/H4/index.js
  src/@ui/typography/H5/index.js
  src/@ui/typography/H6/index.js
  src/@ui/typography/H7/index.js
Labels: merge

#641 Fix feedback link on web
  src/settings/index.js
Labels: merge

#642 Fix distances to have two decimal places
  src/group-finder/GroupCard.js
Labels: merge

#643 Fix the capitalization of titles on thumbnail cards
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  src/@ui/ThumbnailCard/index.js
Labels: merge

#645 Update group single to use nick name instead of first name
  src/group-finder/GroupSingle.js
Labels: merge

#646 Fix issue where canceling a schedule clears your contirubiton history…
  src/@data/withCancelSchedule/index.js
  src/@data/withTransactions/withTransactions.js
  src/give/ContributionHistory/index.js
Labels: merge

#648 Correct font style on Thumbnail Cards
  src/@ui/TaggedContent/index.js
  src/@ui/ThumbnailCard/ThumbnailCard.stories.js
  src/@ui/ThumbnailCard/ThumbnailCard.tests.js
  src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  src/@ui/ThumbnailCard/index.js
Labels: merge

#652 636 Add fontStyle for Safari to display italics
  src/@ui/typography/BodyText/index.js
  src/assets/fonts/DroidSerif.css
Labels: merge

#651 650 Remove space before exclamation point
  src/group-finder/NoResults.js
Labels: merge

#653 Safer rounding on GroupCard
  src/group-finder/GroupCard.js
Labels: merge

#640 Redirect to home page on web logout to prevent endless redirect bug
  src/@ui/NativeWebRouter/ProtectedRoute.js
  src/settings/index.js
Labels: merge

#654 Web issues for v6.0.3
  src/@data/withCancelSchedule/index.js
  src/@data/withTransactions/withTransactions.js
  src/@ui/ConnectedImage/index.js
  src/@ui/NativeWebRouter/ProtectedRoute.js
  src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap
  src/@ui/TaggedContent/index.js
  src/@ui/ThumbnailCard/ThumbnailCard.stories.js
  src/@ui/ThumbnailCard/ThumbnailCard.tests.js
  src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  src/@ui/ThumbnailCard/index.js
  src/@ui/typography/BodyText/index.js
  src/@ui/typography/H1/index.js
  src/@ui/typography/H2/index.js
  src/@ui/typography/H3/index.js
  src/@ui/typography/H4/index.js
  src/@ui/typography/H5/index.js
  src/@ui/typography/H6/index.js
  src/@ui/typography/H7/index.js
  src/assets/fonts/DroidSerif.css
  src/give/ContributionHistory/index.js
  src/group-finder/GroupCard.js
  src/group-finder/GroupSingle.js
  src/group-finder/NoResults.js
  src/settings/index.js
Labels: release

#656 Removed errorLink
  src/@data/Client/errorLink.js
  src/@data/Client/index.js
Labels: ready for review

#659 fix-schedule-giving-dates
  src/@data/withGive/selectors/getOrderDetails.js
Labels: merge

#661 redirect /signup to /login
  src/AppRouter.js
Labels: merge

#664 Fix Signup Route
  src/AppRouter.js
Labels: ready for review
