Repository NewSpring/Apollos, pull requests merged in 2019-03, with the labels that each got.

#775 (SYS-4627) Fixed Two Icons In Drawer
  android/app/src/main/AndroidManifest.xml
Labels: merge

#768 Fund Detail Pages Default Fund Update
  src/@ui/forms/ContributionForm/index.js
  src/give/Funds/FundDetails.js
Labels: merge

#777 Beta -> Master
  android/app/src/main/AndroidManifest.xml
  src/@ui/forms/ContributionForm/index.js
  src/give/Funds/FundDetails.js
Labels: ready for review

#779 Adds PaddedView around group card image
  src/group-finder/GroupCard.js
Labels: ready for review

#780 Centers NS logo on IOS launch screen
  ios/newspring/Supporting/LaunchScreen.xib
  ios/newspring/Supporting/main.m
Labels: ready for review

#781 Release Version 6.1.5
  android/app/build.gradle
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  ios/newspring/Supporting/EXShell.plist
  ios/newspring/Supporting/Info.plist
  package.json
Labels: ready for review

#783 (SYS-4647) Adds Version Number to App
  scripts/bump_version.py
  src/settings/index.js
Labels: merge

#785 (DEV-3623) Added Pre-selection Prop
  src/@ui/forms/ContributionForm/FundInput.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/index.js
Labels: question, ready for review

#786 Beta -> Master
  android/app/build.gradle
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  ios/newspring/Supporting/EXShell.plist
  ios/newspring/Supporting/Info.plist
  ios/newspring/Supporting/LaunchScreen.xib
  ios/newspring/Supporting/main.m
  package.json
  scripts/bump_version.py
  src/@ui/forms/ContributionForm/FundInput.js
  src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
  src/@ui/forms/ContributionForm/index.js
  src/group-finder/GroupCard.js
  src/settings/index.js
Labels: ready for review

#787 Release v6.1.6
  android/app/build.gradle
  android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
  ios/newspring/Supporting/EXShell.plist
  ios/newspring/Supporting/Info.plist
  package.json
  src/settings/index.js
Labels: ready for review
